### ISSUE TITLE
Error about loading finetuned model

### ISSUE THREAD

**Issue by o0t1ng0o** [hyn2028/llm-cxr#5]
Hi @hyn2028,

I meet this error when I load the finetuned model.

Traceback (most recent call last):
  File "test.py", line 347, in <module>
    main()
  File "test.py", line 197, in main
    model, tokenizer = load_model_tokenizer_for_generate_separate(args.config_path, args.model_path)
  File "./llm-cxr/training/generate.py", line 57, in load_model_tokenizer_for_generate_separate
    model = AutoModelForCausalLM.from_pretrained(
  File "../transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "../transformers/modeling_utils.py", line 2405, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory 
 ./checkpoints/llmcxr_origin_report__2023-06-19_00-13-51.

This are my saved files. Did the training code save the model? 
![image](https://github.com/hyn2028/llm-cxr/assets/16815652/b8ca223a-2581-417e-88b9-d4f64c07735a)

Thank you in advance.

**Comment by o0t1ng0o** [comment]
I found that I can use zero_to_fp32.py to generate the model 'pytorch_model.bin'
